# Generated by Django 5.1.1 on 2025-02-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view', 'can_view'), ('can_create', 'can_create'), ('can_edit', 'can_edit'), ('can_delete', 'can_delete')]},
        ),
    ]
