# Generated by Django 5.1.1 on 2025-03-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags_alter_tag_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
    ]
